### ISSUE TITLE
reviews on docs

### ISSUE THREAD

**Issue by mostafarow** [sesamiapp/devportal#1]

**Comment by mostafarow** [comment]
#### anatomy-of-sesami-button
- in product-id section, theres an extra `the` in sentence: if **the** you are rendering the button 
- in variant-id section, because the variant-id should always come with the product-id, i think in the sample code its better to add the product-id attribute to emphasize that. people may just copy-paste the sample code and dont read the descriptions to the end.

**Comment by mostafarow** [comment]
#### multiple-product-forms
in example2, because the additional button is for another product, i think its better to change the product object like this:
```html
<div class="upsell-product">
  <div class="sesami__additionalButtonWrapper" data-sesami-product-id="{{upsellProduct.id}}"></div>
```

**Comment by rmtngh** [comment]
Thanks @mostafarow,
Issues are fixed and deployed,
Regarding:

> in example2, because the additional button is for another product, i think its better to change the product object like this:

we are using `liquid` variables here, it is a template language used by Shopify, and `product` can refer to different products inside a loop or any other context. Using a custom variable might be more confusing as they won't know how to create one, but this one will at least work even if it is used in the same context, then they can debug it and provide a different product.
